Repository jetstack/version-checker, pull requests merged in 2020-09, with the labels that each got.

#46 Client improvements
  cmd/app/options.go
  cmd/app/options_test.go
  pkg/client/acr/acr.go
  pkg/client/client.go
  pkg/client/client_test.go
  pkg/client/docker/docker.go
  pkg/client/docker/path.go
  pkg/client/docker/path_test.go
  pkg/client/ecr/ecr.go
  pkg/client/ecr/ecr_test.go
  pkg/client/gcr/gcr.go
  pkg/client/quay/quay.go
  pkg/client/selfhosted/path.go
  pkg/client/selfhosted/path_test.go
  pkg/client/selfhosted/selfhosted.go
  pkg/client/util/util.go
  pkg/client/util/util_test.go
Labels: approved, dco-signoff: yes, lgtm, size/XL

#47 Updates helm chart to enable multiple selfhosted registries
  deploy/charts/version-checker/templates/deployment.yaml
  deploy/charts/version-checker/templates/secret.yaml
  deploy/charts/version-checker/values.yaml
Labels: approved, dco-signoff: yes, lgtm, size/L

#48 Update 0.2.0
  Makefile
  README.md
  deploy/charts/version-checker/Chart.yaml
  deploy/charts/version-checker/values.yaml
  deploy/yaml/deploy.yaml
Labels: approved, dco-signoff: yes, lgtm, size/M

#50 Add link to preflight in README
  README.md
Labels: approved, dco-signoff: yes, lgtm, size/XS

#51 Add yaml deploy kustomization file
  README.md
  deploy/yaml/kustomization.yaml
Labels: approved, dco-signoff: yes, lgtm, ok-to-test, size/XS
