Repository jetstack/version-checker, pull requests merged in 2020-08, with the labels that each got.

#1 Adds note that the tool is currently experimental
  README.md
Labels: approved, dco-signoff: yes, size/XS

#4 Adds contributing and code of conduct md files.
  CODE_OF_CONDUCT.md
  CONTRIBUTING.md
Labels: approved, dco-signoff: yes, size/L

#2 feat: allow additional labels on servicemonitor
  deploy/charts/version-checker/templates/servicemonitor.yaml
  deploy/charts/version-checker/values.yaml
Labels: approved, dco-signoff: yes, lgtm, size/XS

#5 Fixes regex README.md example
  README.md
Labels: approved, dco-signoff: yes, size/XS

#6 fix typo
  README.md
Labels: approved, dco-signoff: yes, lgtm, size/XS

#9 Fix continer -> container spelling in README.md
  README.md
Labels: approved, dco-signoff: yes, size/XS

#12 fix: do not warn when falling back to SHA comparison
  pkg/controller/sync.go
Labels: approved, dco-signoff: yes, lgtm, size/XS

#15 Adds test + verify to Makefile
  Makefile
Labels: approved, dco-signoff: yes, lgtm, size/XS

#16 Better client parsing
  pkg/client/client.go
  pkg/client/client_test.go
  pkg/client/docker/docker.go
  pkg/client/docker/path.go
  pkg/client/docker/path_test.go
  pkg/client/gcr/gcr.go
  pkg/client/gcr/path.go
  pkg/client/gcr/path_test.go
  pkg/client/quay/path.go
  pkg/client/quay/path_test.go
  pkg/client/quay/quay.go
Labels: approved, dco-signoff: yes, lgtm, size/XL

#18 Move starting the garbage collectors outside of New
  cmd/app/app.go
  pkg/controller/cache.go
  pkg/controller/controller.go
  pkg/version/cache.go
  pkg/version/version.go
Labels: approved, dco-signoff: yes, lgtm, size/L

#19 Fix regex example in README
  README.md
Labels: approved, dco-signoff: yes, lgtm

#20 Handle sha+version, and Pod deletion/updating
  go.mod
  pkg/api/types.go
  pkg/controller/cache.go
  pkg/controller/controller.go
  pkg/controller/scheduler/scheduler.go
  pkg/controller/scheduler/scheduler_test.go
  pkg/controller/sync.go
  pkg/controller/sync_test.go
  pkg/metrics/metrics.go
  pkg/version/errors/errors.go
  pkg/version/semver/semver.go
  pkg/version/version.go
Labels: approved, dco-signoff: yes, lgtm, size/XL

#25 Fix regex example dot
  README.md
Labels: approved, dco-signoff: yes, lgtm, size/XS

#26 Updates chart and Makefile to v0.1.1
  Makefile
  deploy/charts/version-checker/Chart.yaml
  deploy/charts/version-checker/values.yaml
  deploy/yaml/deploy.yaml
Labels: approved, dco-signoff: yes, lgtm, size/S

#36 docs(readme): verison -> version
  README.md
Labels: approved, dco-signoff: yes, lgtm, ok-to-test, size/XS

#34 Adds an info log when test-all-containers is false
  cmd/app/app.go
Labels: approved, dco-signoff: yes, lgtm, ok-to-test, size/XS

#32 Break out image and search caches into generic cache
  cmd/app/app.go
  go.mod
  pkg/api/types.go
  pkg/cache/cache.go
  pkg/controller/cache.go
  pkg/controller/controller.go
  pkg/controller/search/search.go
  pkg/controller/sync.go
  pkg/version/cache.go
  pkg/version/version.go
Labels: approved, dco-signoff: yes, lgtm, size/L

#40 Add URL override
  README.md
  pkg/api/types.go
  pkg/controller/sync.go
  pkg/version/version.go
Labels: approved, dco-signoff: yes, lgtm, size/M

#44 Moves controller options into sub module with tests
  pkg/controller/options/options.go
  pkg/controller/options/options_test.go
  pkg/controller/sync.go
Labels: approved, dco-signoff: yes, lgtm, size/L

#45 Adds controller testing
  pkg/controller/checker/checker.go
  pkg/controller/checker/checker_test.go
  pkg/controller/controller.go
  pkg/controller/internal/fake/search/search.go
  pkg/controller/options/options.go
  pkg/controller/options/options_test.go
  pkg/controller/search/search.go
  pkg/controller/sync.go
  pkg/controller/sync_test.go
  pkg/metrics/metrics.go
Labels: approved, dco-signoff: yes, lgtm, size/XXL

#41 Feature/selfhosted
  cmd/app/app.go
  deploy/charts/version-checker/templates/deployment.yaml
  deploy/charts/version-checker/templates/secret.yaml
  deploy/charts/version-checker/values.yaml
  pkg/client/client.go
  pkg/client/client_test.go
  pkg/client/docker/path_test.go
  pkg/client/gcr/path_test.go
  pkg/client/quay/path_test.go
  pkg/client/selfhosted/errors/errors.go
  pkg/client/selfhosted/path.go
  pkg/client/selfhosted/path_test.go
  pkg/client/selfhosted/selfhosted.go
Labels: approved, dco-signoff: yes, lgtm, needs-ok-to-test, size/XL

#42 Adds ACR image client
  cmd/app/app.go
  deploy/charts/version-checker/templates/deployment.yaml
  deploy/charts/version-checker/templates/secret.yaml
  deploy/charts/version-checker/values.yaml
  go.mod
  pkg/client/acr/acr.go
  pkg/client/acr/acr_test.go
  pkg/client/acr/path.go
  pkg/client/acr/path_test.go
  pkg/client/client.go
  pkg/client/client_test.go
  pkg/client/docker/docker.go
Labels: approved, dco-signoff: yes, lgtm, size/XL

#38 Adds support for ECR
  cmd/app/app.go
  cmd/app/options.go
  deploy/charts/version-checker/templates/deployment.yaml
  deploy/charts/version-checker/templates/secret.yaml
  deploy/charts/version-checker/values.yaml
  go.mod
  go.sum
  pkg/client/client.go
  pkg/client/client_test.go
  pkg/client/ecr/ecr.go
  pkg/client/ecr/ecr_test.go
  pkg/client/ecr/path.go
  pkg/client/ecr/path_test.go
Labels: approved, dco-signoff: yes, lgtm, size/XL

#39 Adds named flag sets
  cmd/app/app.go
  cmd/app/options.go
  go.mod
  go.sum
  pkg/client/docker/docker.go
Labels: approved, dco-signoff: yes, lgtm, size/L
