Repository jetstack/version-checker, pull requests merged in 2022-08, with the labels that each got.

#86 Add myself as owner
  OWNERS
Labels: dco-signoff: yes, approved, size/XS, lgtm, release-note

#85 Adding GHCR.io Support
  cmd/app/options.go
  cmd/app/options_test.go
  go.mod
  go.sum
  pkg/client/client.go
  pkg/client/client_test.go
  pkg/client/ghcr/ghcr.go
  pkg/client/ghcr/path.go
  pkg/client/ghcr/path_test.go
Labels: dco-signoff: yes, approved, size/L, lgtm, release-note

#84 Support Google Artifact Registry
  pkg/client/gcr/path.go
  pkg/client/gcr/path_test.go
Labels: dco-signoff: yes, approved, lgtm, size/S, release-note

#79 added the option to use a AWS role ARN to authenticate to ECR if on EKS
  cmd/app/options.go
  cmd/app/options_test.go
  deploy/charts/version-checker/templates/deployment.yaml
  deploy/charts/version-checker/templates/serviceaccount.yaml
  deploy/charts/version-checker/values.yaml
  pkg/client/ecr/ecr.go
Labels: dco-signoff: yes, approved, lgtm, needs-ok-to-test, size/M, release-note
