Repository jetstack/version-checker, pull requests merged in 2023-07, with the labels that each got.

#91 Sets API version of Role and RoleBinding to v1
  deploy/charts/version-checker/Chart.yaml
  deploy/charts/version-checker/templates/prometheus.yaml
Labels: dco-signoff: yes, size/XS, needs-ok-to-test, do-not-merge/release-note-label-needed

#87 Fix docker authorization header value
  pkg/client/docker/docker.go
Labels: dco-signoff: yes, size/XS, needs-ok-to-test, do-not-merge/release-note-label-needed

#71 Replaced `docker` with `image`
  Makefile
Labels: size/XS, dco-signoff: no, lgtm, do-not-merge/release-note-label-needed

#100 Allow for overriding Token Path
  cmd/app/options.go
  cmd/app/options_test.go
  pkg/client/selfhosted/selfhosted.go
Labels: size/M

#99 Increase the number of Tags fetched for Docker Registries
  pkg/client/docker/docker.go
Labels: size/XS

#98 Adding k8s.io support
  pkg/client/client_test.go
  pkg/client/gcr/path.go
  pkg/client/gcr/path_test.go
Labels: size/S

#95 Better support for selfHosted and SSL connections
  cmd/app/app.go
  cmd/app/options.go
  cmd/app/options_test.go
  pkg/client/quay/quay.go
  pkg/client/selfhosted/selfhosted.go
  pkg/controller/checker/checker.go
Labels: size/L

#96 Sync InitContainers
  pkg/client/client.go
  pkg/controller/checker/checker.go
  pkg/controller/controller.go
  pkg/controller/sync.go
  pkg/metrics/metrics.go
Labels: size/M

#105 Adding simple healthz and readyz endpoints
  deploy/charts/version-checker/templates/deployment.yaml
  deploy/charts/version-checker/values.yaml
  deploy/yaml/deploy.yaml
  pkg/controller/sync.go
  pkg/metrics/metrics.go
Labels: size/M

#106 Release update files
  .github/workflows/release.yaml
  Makefile
  cmd/app/options.go
  deploy/charts/version-checker/Chart.yaml
Labels: size/M

#107 Release v0.2.5
  deploy/yaml/deploy.yaml
Labels: size/XS
